#' Equities Taxonomy
#'
#' Returns taxonomy mapping for equities: sector -> subsector -> industry.
#'
#' @return A tibble with columns: sector, subsector, industry
#' @export
#' @keywords internal
equities_taxonomy <- function() {
  tibble::tribble(
    ~sector                  , ~subsector                   , ~industry                                  ,
    # BASIC MATERIALS
    "BASIC MATERIALS"        , "CHEMICALS"                  , "SPECIALTY CHEMICALS"                      ,
    "BASIC MATERIALS"        , "CHEMICALS"                  , "CHEMICALS"                                ,
    "BASIC MATERIALS"        , "CHEMICALS"                  , "AGRICULTURAL INPUTS"                      ,
    "BASIC MATERIALS"        , "METALS & MINING"            , "STEEL"                                    ,
    "BASIC MATERIALS"        , "METALS & MINING"            , "ALUMINUM"                                 ,
    "BASIC MATERIALS"        , "METALS & MINING"            , "COPPER"                                   ,
    "BASIC MATERIALS"        , "METALS & MINING"            , "OTHER INDUSTRIAL METALS & MINING"         ,
    "BASIC MATERIALS"        , "METALS & MINING"            , "COKING COAL"                              ,
    "BASIC MATERIALS"        , "PRECIOUS METALS"            , "GOLD"                                     ,
    "BASIC MATERIALS"        , "PRECIOUS METALS"            , "OTHER PRECIOUS METALS & MINING"           ,
    "BASIC MATERIALS"        , "CONSTRUCTION MATERIALS"     , "BUILDING MATERIALS"                       ,
    "BASIC MATERIALS"        , "FOREST PRODUCTS"            , "LUMBER & WOOD PRODUCTION"                 ,
    "BASIC MATERIALS"        , "FOREST PRODUCTS"            , "PAPER & PAPER PRODUCTS"                   ,
    # COMMUNICATION SERVICES
    "COMMUNICATION SERVICES" , "INTERNET PLATFORMS"         , "INTERNET CONTENT & INFORMATION"           ,
    "COMMUNICATION SERVICES" , "INTERNET PLATFORMS"         , "ADVERTISING AGENCIES"                     ,
    "COMMUNICATION SERVICES" , "MEDIA"                      , "ENTERTAINMENT"                            ,
    "COMMUNICATION SERVICES" , "MEDIA"                      , "BROADCASTING"                             ,
    "COMMUNICATION SERVICES" , "MEDIA"                      , "ELECTRONIC GAMING & MULTIMEDIA"           ,
    "COMMUNICATION SERVICES" , "MEDIA"                      , "PUBLISHING"                               ,
    "COMMUNICATION SERVICES" , "TELECOM"                    , "TELECOM SERVICES"                         ,
    # CONSUMER CYCLICAL
    "CONSUMER CYCLICAL"      , "HOSPITALITY & LEISURE"      , "RESTAURANTS"                              ,
    "CONSUMER CYCLICAL"      , "HOSPITALITY & LEISURE"      , "LEISURE"                                  ,
    "CONSUMER CYCLICAL"      , "HOSPITALITY & LEISURE"      , "TRAVEL SERVICES"                          ,
    "CONSUMER CYCLICAL"      , "HOSPITALITY & LEISURE"      , "RESORTS & CASINOS"                        ,
    "CONSUMER CYCLICAL"      , "HOSPITALITY & LEISURE"      , "LODGING"                                  ,
    "CONSUMER CYCLICAL"      , "HOSPITALITY & LEISURE"      , "GAMBLING"                                 ,
    "CONSUMER CYCLICAL"      , "AUTOMOTIVE"                 , "AUTO PARTS"                               ,
    "CONSUMER CYCLICAL"      , "AUTOMOTIVE"                 , "AUTO & TRUCK DEALERSHIPS"                 ,
    "CONSUMER CYCLICAL"      , "AUTOMOTIVE"                 , "RECREATIONAL VEHICLES"                    ,
    "CONSUMER CYCLICAL"      , "AUTOMOTIVE"                 , "AUTO MANUFACTURERS"                       ,
    "CONSUMER CYCLICAL"      , "RETAIL"                     , "SPECIALTY RETAIL"                         ,
    "CONSUMER CYCLICAL"      , "RETAIL"                     , "INTERNET RETAIL"                          ,
    "CONSUMER CYCLICAL"      , "RETAIL"                     , "HOME IMPROVEMENT RETAIL"                  ,
    "CONSUMER CYCLICAL"      , "RETAIL"                     , "DEPARTMENT STORES"                        ,
    "CONSUMER CYCLICAL"      , "HOUSING & SHELTER"          , "RESIDENTIAL CONSTRUCTION"                 ,
    "CONSUMER CYCLICAL"      , "HOUSING & SHELTER"          , "FURNISHINGS, FIXTURES & APPLIANCES"       ,
    "CONSUMER CYCLICAL"      , "HOUSING & SHELTER"          , "PERSONAL SERVICES"                        ,
    "CONSUMER CYCLICAL"      , "APPAREL & ACCESSORIES"      , "APPAREL RETAIL"                           ,
    "CONSUMER CYCLICAL"      , "APPAREL & ACCESSORIES"      , "APPAREL MANUFACTURING"                    ,
    "CONSUMER CYCLICAL"      , "APPAREL & ACCESSORIES"      , "FOOTWEAR & ACCESSORIES"                   ,
    "CONSUMER CYCLICAL"      , "APPAREL & ACCESSORIES"      , "LUXURY GOODS"                             ,
    "CONSUMER CYCLICAL"      , "APPAREL & ACCESSORIES"      , "TEXTILE MANUFACTURING"                    ,
    "CONSUMER CYCLICAL"      , "PACKAGING"                  , "PACKAGING & CONTAINERS"                   ,
    # CONSUMER DEFENSIVE
    "CONSUMER DEFENSIVE"     , "FOOD & BEVERAGE"            , "PACKAGED FOODS"                           ,
    "CONSUMER DEFENSIVE"     , "FOOD & BEVERAGE"            , "BEVERAGES - NON-ALCOHOLIC"                ,
    "CONSUMER DEFENSIVE"     , "FOOD & BEVERAGE"            , "FARM PRODUCTS"                            ,
    "CONSUMER DEFENSIVE"     , "FOOD & BEVERAGE"            , "CONFECTIONERS"                            ,
    "CONSUMER DEFENSIVE"     , "FOOD RETAIL & DISTRIBUTION" , "DISCOUNT STORES"                          ,
    "CONSUMER DEFENSIVE"     , "FOOD RETAIL & DISTRIBUTION" , "FOOD DISTRIBUTION"                        ,
    "CONSUMER DEFENSIVE"     , "FOOD RETAIL & DISTRIBUTION" , "GROCERY STORES"                           ,
    "CONSUMER DEFENSIVE"     , "HOUSEHOLD PRODUCTS"         , "HOUSEHOLD & PERSONAL PRODUCTS"            ,
    "CONSUMER DEFENSIVE"     , "EDUCATION"                  , "EDUCATION & TRAINING SERVICES"            ,
    "CONSUMER DEFENSIVE"     , "ALCOHOL & TOBACCO"          , "TOBACCO"                                  ,
    "CONSUMER DEFENSIVE"     , "ALCOHOL & TOBACCO"          , "BEVERAGES - BREWERS"                      ,
    "CONSUMER DEFENSIVE"     , "ALCOHOL & TOBACCO"          , "BEVERAGES - WINERIES & DISTILLERIES"      ,
    # ENERGY
    "ENERGY"                 , "OIL & GAS PRODUCTION"       , "OIL & GAS E&P"                            ,
    "ENERGY"                 , "OIL & GAS PRODUCTION"       , "OIL & GAS DRILLING"                       ,
    "ENERGY"                 , "OIL & GAS PRODUCTION"       , "OIL & GAS INTEGRATED"                     ,
    "ENERGY"                 , "OIL & GAS SERVICES"         , "OIL & GAS EQUIPMENT & SERVICES"           ,
    "ENERGY"                 , "OIL & GAS SERVICES"         , "OIL & GAS REFINING & MARKETING"           ,
    "ENERGY"                 , "OIL & GAS SERVICES"         , "OIL & GAS MIDSTREAM"                      ,
    "ENERGY"                 , "OTHER ENERGY"               , "URANIUM"                                  ,
    "ENERGY"                 , "OTHER ENERGY"               , "THERMAL COAL"                             ,
    # FINANCIAL SERVICES
    "FINANCIAL SERVICES"     , "BANKING"                    , "BANKS - REGIONAL"                         ,
    "FINANCIAL SERVICES"     , "BANKING"                    , "BANKS - DIVERSIFIED"                      ,
    "FINANCIAL SERVICES"     , "CAPITAL MARKETS"            , "ASSET MANAGEMENT"                         ,
    "FINANCIAL SERVICES"     , "CAPITAL MARKETS"            , "CAPITAL MARKETS"                          ,
    "FINANCIAL SERVICES"     , "CAPITAL MARKETS"            , "CREDIT SERVICES"                          ,
    "FINANCIAL SERVICES"     , "CAPITAL MARKETS"            , "FINANCIAL CONGLOMERATES"                  ,
    "FINANCIAL SERVICES"     , "CAPITAL MARKETS"            , "MORTGAGE FINANCE"                         ,
    "FINANCIAL SERVICES"     , "CAPITAL MARKETS"            , "SHELL COMPANIES"                          ,
    "FINANCIAL SERVICES"     , "INSURANCE"                  , "INSURANCE - PROPERTY & CASUALTY"          ,
    "FINANCIAL SERVICES"     , "INSURANCE"                  , "INSURANCE - SPECIALTY"                    ,
    "FINANCIAL SERVICES"     , "INSURANCE"                  , "INSURANCE - LIFE"                         ,
    "FINANCIAL SERVICES"     , "INSURANCE"                  , "INSURANCE BROKERS"                        ,
    "FINANCIAL SERVICES"     , "INSURANCE"                  , "INSURANCE - REINSURANCE"                  ,
    "FINANCIAL SERVICES"     , "INSURANCE"                  , "INSURANCE - DIVERSIFIED"                  ,
    "FINANCIAL SERVICES"     , "FINANCIAL INFRASTRUCTURE"   , "FINANCIAL DATA & STOCK EXCHANGES"         ,
    # HEALTHCARE
    "HEALTHCARE"             , "BIO PHARMA"                 , "BIOTECHNOLOGY"                            ,
    "HEALTHCARE"             , "BIO PHARMA"                 , "DRUG MANUFACTURERS - SPECIALTY & GENERIC" ,
    "HEALTHCARE"             , "BIO PHARMA"                 , "DRUG MANUFACTURERS - GENERAL"             ,
    "HEALTHCARE"             , "MEDICAL EQUIPMENT"          , "MEDICAL DEVICES"                          ,
    "HEALTHCARE"             , "MEDICAL EQUIPMENT"          , "DIAGNOSTICS & RESEARCH"                   ,
    "HEALTHCARE"             , "MEDICAL EQUIPMENT"          , "MEDICAL INSTRUMENTS & SUPPLIES"           ,
    "HEALTHCARE"             , "HEALTHCARE SERVICES"        , "MEDICAL CARE FACILITIES"                  ,
    "HEALTHCARE"             , "HEALTHCARE SERVICES"        , "HEALTH INFORMATION SERVICES"              ,
    "HEALTHCARE"             , "HEALTHCARE SERVICES"        , "HEALTHCARE PLANS"                         ,
    "HEALTHCARE"             , "HEALTHCARE SERVICES"        , "MEDICAL DISTRIBUTION"                     ,
    # INDUSTRIALS
    "INDUSTRIALS"            , "MACHINERY & EQUIPMENT"      , "SPECIALTY INDUSTRIAL MACHINERY"           ,
    "INDUSTRIALS"            , "MACHINERY & EQUIPMENT"      , "FARM & HEAVY CONSTRUCTION MACHINERY"      ,
    "INDUSTRIALS"            , "MACHINERY & EQUIPMENT"      , "ELECTRICAL EQUIPMENT & PARTS"             ,
    "INDUSTRIALS"            , "MACHINERY & EQUIPMENT"      , "TOOLS & ACCESSORIES"                      ,
    "INDUSTRIALS"            , "CONSTRUCTION"               , "ENGINEERING & CONSTRUCTION"               ,
    "INDUSTRIALS"            , "CONSTRUCTION"               , "BUILDING PRODUCTS & EQUIPMENT"            ,
    "INDUSTRIALS"            , "CONSTRUCTION"               , "INDUSTRIAL DISTRIBUTION"                  ,
    "INDUSTRIALS"            , "CONSTRUCTION"               , "METAL FABRICATION"                        ,
    "INDUSTRIALS"            , "INDUSTRIAL SERVICES"        , "SPECIALTY BUSINESS SERVICES"              ,
    "INDUSTRIALS"            , "INDUSTRIAL SERVICES"        , "RENTAL & LEASING SERVICES"                ,
    "INDUSTRIALS"            , "INDUSTRIAL SERVICES"        , "STAFFING & EMPLOYMENT SERVICES"           ,
    "INDUSTRIALS"            , "INDUSTRIAL SERVICES"        , "CONSULTING SERVICES"                      ,
    "INDUSTRIALS"            , "INDUSTRIAL SERVICES"        , "SECURITY & PROTECTION SERVICES"           ,
    "INDUSTRIALS"            , "INDUSTRIAL SERVICES"        , "WASTE MANAGEMENT"                         ,
    "INDUSTRIALS"            , "INDUSTRIAL SERVICES"        , "POLLUTION & TREATMENT CONTROLS"           ,
    "INDUSTRIALS"            , "INDUSTRIAL SERVICES"        , "BUSINESS EQUIPMENT & SUPPLIES"            ,
    "INDUSTRIALS"            , "AEROSPACE & DEFENSE"        , "AEROSPACE & DEFENSE"                      ,
    "INDUSTRIALS"            , "TRANSPORTATION"             , "INTEGRATED FREIGHT & LOGISTICS"           ,
    "INDUSTRIALS"            , "TRANSPORTATION"             , "TRUCKING"                                 ,
    "INDUSTRIALS"            , "TRANSPORTATION"             , "AIRLINES"                                 ,
    "INDUSTRIALS"            , "TRANSPORTATION"             , "RAILROADS"                                ,
    "INDUSTRIALS"            , "TRANSPORTATION"             , "MARINE SHIPPING"                          ,
    "INDUSTRIALS"            , "TRANSPORTATION"             , "AIRPORTS & AIR SERVICES"                  ,
    "INDUSTRIALS"            , "CONGLOMERATES"              , "CONGLOMERATES"                            ,
    # REAL ESTATE
    "REAL ESTATE"            , "EQUITY REITs"               , "REIT - RESIDENTIAL"                       ,
    "REAL ESTATE"            , "EQUITY REITs"               , "REIT - OFFICE"                            ,
    "REAL ESTATE"            , "EQUITY REITs"               , "REIT - RETAIL"                            ,
    "REAL ESTATE"            , "EQUITY REITs"               , "REIT - INDUSTRIAL"                        ,
    "REAL ESTATE"            , "EQUITY REITs"               , "REIT - SPECIALTY"                         ,
    "REAL ESTATE"            , "EQUITY REITs"               , "REIT - HEALTHCARE FACILITIES"             ,
    "REAL ESTATE"            , "EQUITY REITs"               , "REIT - HOTEL & MOTEL"                     ,
    "REAL ESTATE"            , "EQUITY REITs"               , "REIT - DIVERSIFIED"                       ,
    "REAL ESTATE"            , "MORTGAGE REITs"             , "REIT - MORTGAGE"                          ,
    "REAL ESTATE"            , "REAL ESTATE SERVICES"       , "REAL ESTATE SERVICES"                     ,
    "REAL ESTATE"            , "REAL ESTATE SERVICES"       , "REAL ESTATE - DEVELOPMENT"                ,
    # TECHNOLOGY
    "TECHNOLOGY"             , "SOFTWARE"                   , "SOFTWARE - APPLICATION"                   ,
    "TECHNOLOGY"             , "SOFTWARE"                   , "SOFTWARE - INFRASTRUCTURE"                ,
    "TECHNOLOGY"             , "SEMICONDUCTORS"             , "SEMICONDUCTORS"                           ,
    "TECHNOLOGY"             , "SEMICONDUCTORS"             , "SEMICONDUCTOR EQUIPMENT & MATERIALS"      ,
    "TECHNOLOGY"             , "HARDWARE"                   , "ELECTRONIC COMPONENTS"                    ,
    "TECHNOLOGY"             , "HARDWARE"                   , "COMMUNICATION EQUIPMENT"                  ,
    "TECHNOLOGY"             , "HARDWARE"                   , "SCIENTIFIC & TECHNICAL INSTRUMENTS"       ,
    "TECHNOLOGY"             , "HARDWARE"                   , "COMPUTER HARDWARE"                        ,
    "TECHNOLOGY"             , "HARDWARE"                   , "ELECTRONICS & COMPUTER DISTRIBUTION"      ,
    "TECHNOLOGY"             , "HARDWARE"                   , "SOLAR"                                    ,
    "TECHNOLOGY"             , "HARDWARE"                   , "CONSUMER ELECTRONICS"                     ,
    "TECHNOLOGY"             , "IT SERVICES"                , "INFORMATION TECHNOLOGY SERVICES"          ,
    # UTILITIES
    "UTILITIES"              , "REGULATED UTILITIES"        , "UTILITIES - REGULATED ELECTRIC"           ,
    "UTILITIES"              , "REGULATED UTILITIES"        , "UTILITIES - REGULATED GAS"                ,
    "UTILITIES"              , "REGULATED UTILITIES"        , "UTILITIES - REGULATED WATER"              ,
    "UTILITIES"              , "REGULATED UTILITIES"        , "UTILITIES - DIVERSIFIED"                  ,
    "UTILITIES"              , "INDEPENDENT POWER"          , "UTILITIES - INDEPENDENT POWER PRODUCERS"  ,
    "UTILITIES"              , "INDEPENDENT POWER"          , "UTILITIES - RENEWABLE"
  )
}
